name: Node-js CI
on:
 
  workflow_dispatch:

permissions:
  contents: read # to fetch code (actions/checkout)

jobs:


  nodebuild:
    name: build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
    - name: Use Node.js 22.x
      uses: actions/setup-node@v4
      with:
        node-version: 22.x
    - name: Install Dependencies
      run: npm install
    - name: Lint
      run: npm run lint

  check-engines:
    name: package 
    runs-on: ubuntu-latest
    needs: test
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
    - name: Use Node.js 22.x
      uses: actions/setup-node@v4
      with:
        node-version: 22.x
    - name: Install Dependencies
      run: npm install
    - name: Check Engines
      run: |
        # TODO: move this to its own action
        npm install @npmcli/arborist@7 semver@7 --no-save
        node .github/scripts/check-engines.js
  test:
    name: Test 
    runs-on: ubuntu-latest
    needs: nodebuild
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
    - name: Use Node.js 22.x
      uses: actions/setup-node@v4
      with:
        node-version: 22.x
    - name: Update npm
      run: npm install npm@latest -g
    - name: Install Dependencies
      run: npm install
    - name: Pack
      id: pack
      env:
        NODE_GYP_TEMP_DIR: '${{ runner.temp }}/node-gyp'
      run: |
        mkdir -p $NODE_GYP_TEMP_DIR
        npm pack
        tar xzf *.tgz -C $NODE_GYP_TEMP_DIR --strip-components=1
        cp -r test/ $NODE_GYP_TEMP_DIR/test/
        echo "dir=$NODE_GYP_TEMP_DIR" >> "$GITHUB_OUTPUT"
    - name: Test
      working-directory: ${{ steps.pack.outputs.dir }}
      env:
        FULL_TEST: '1'
      run: |
        npm install
        npm test
  call-reusable:
    name: Call Reusable Workflow
    needs: nodebuild
    uses: ./.github/workflows/reuseable.yml
